name: Build, Test, and Containerize the App

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [client, simplehood_api, simDAQ_api]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies and build the app
        run: |
          sudo apt install curl 
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
          # Customize the nodejs version for each service
          if [ "${{ matrix.service }}" == "client" ]; then
            nvm install 16.13.0-alpine && nvm use 16.13.0-alpine
          elif [ "${{ matrix.service }}" == "simplehood_api" ]; then
            nvm install 14.20.1-alpine && nvm use 14.20.1-alpine
          elif [ "${{ matrix.service }}" == "simDAQ_api" ]; then
            nvm install 14.20.1-alpine && nvm use 14.20.1-alpine
          fi
          cd ./${{ matrix.service }} && yarn dev

      - name: Run tests
        run: |
          cd ./${{ matrix.service }} && yarn test

      - name: Build the Docker image
        run: |
          cd ./${{ matrix.service }}
          docker build -t ${{ matrix.service }} -f ./${{ matrix.service }}/Dockerfile .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag ${{ matrix.service }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest

  
